force-app/main/default/objects/Apex_Log__c/Apex_Log__c.object-meta.xml
<CustomObject>
    <label>Apex Log</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Apex Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
    <pluralLabel>Apex Logs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Apex_Log__c/fields/Exception__c.field-meta.xml
<CustomField>
    <fullName>Exception__c</fullName>
    <label>Exception</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/ExceptionType__c.field-meta.xml
<CustomField>
    <fullName>ExceptionType__c</fullName>
    <label>ExceptionType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>System.AsyncException</fullName>
            </value>
            <value>
                <fullName>System.BigObjectException</fullName>
            </value>
            <value>
                <fullName>System.CalloutException</fullName>
            </value>
            <value>
                <fullName>System.DmlException</fullName>
            </value>
            <value>
                <fullName>System.EmailException</fullName>
            </value>
            <value>
                <fullName>System.ExternalObjectException</fullName>
            </value>
            <value>
                <fullName>System.IllegalArgumentException</fullName>
            </value>
            <value>
                <fullName>System.InvalidParameterValueException</fullName>
            </value>
            <value>
                <fullName>System.LimitException</fullName>
            </value>
            <value>
                <fullName>System.JSONException</fullName>
            </value>
            <value>
                <fullName>System.ListException</fullName>
            </value>
            <value>
                <fullName>System.MathException</fullName>
            </value>
            <value>
                <fullName>System.NoAccessException</fullName>
            </value>
            <value>
                <fullName>System.NoDataFoundException</fullName>
            </value>
            <value>
                <fullName>System.NoSuchElementException</fullName>
            </value>
            <value>
                <fullName>System.NullPointerException</fullName>
            </value>
            <value>
                <fullName>System.QueryException</fullName>
            </value>
            <value>
                <fullName>System.RequiredFeatureMissing</fullName>
            </value>
            <value>
                <fullName>System.SearchException</fullName>
            </value>
            <value>
                <fullName>System.SecurityException</fullName>
            </value>
            <value>
                <fullName>System.SerializationException</fullName>
            </value>
            <value>
                <fullName>System.SObjectException</fullName>
            </value>
            <value>
                <fullName>System.StringException</fullName>
            </value>
            <value>
                <fullName>System.TypeException</fullName>
            </value>
            <value>
                <fullName>System.VisualforceException</fullName>
            </value>
            <value>
                <fullName>System.XmlException</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Log__c/fields/WithException__c.field-meta.xml
<CustomField>
    <fullName>WithException__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WithException</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Apex_Log_Setting__mdt/Apex_Log_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Apex Log Setting</label>
    <pluralLabel>Apex Log Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Apex_Log_Setting__mdt/fields/SpecifyClasses__c.field-meta.xml
<CustomField>
    <fullName>SpecifyClasses__c</fullName>
    <label>SpecifyClasses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ApexLoggerData.cls
/*
    功能描述：ApexLogger数据类
    创建标识：hpc 2020-08
*/
public class ApexLoggerData {
    //自定义空白异常
    private static final ApexLoggerUtil.BlankException BLANK_EXCEPTION = new ApexLoggerUtil.BlankException();

    //通过System.debug输出
    public Boolean OutputSystemDebugLogs{get;set;}
    //记录到Database
    public Boolean OutputDatabaseLogs{get;set;}
    //仅记录指定Class的Logs
    public Boolean OutputOnlySpecifyClassLogs{get;set;}
    //界面显示异常
    public Boolean UIShowException{get;set;}
    //界面输出详细Exceptions
    public Boolean UIDisplayDetailExceptions{get;set;}
    //界面输出友好Exceptions
    public Boolean UIDisplayFriendlyExceptions{get;set;}
    //指定Class
    public String SpecifyClasses{get;set;}
    //是否分批处理
    public Boolean IsBatches{get;set;}
    //ApexLog待处理集合
    public List<Apex_Log__c> ApexBatches{get;set;}

    //构造方法
    public ApexLoggerData() {
        IsBatches=false;
        ApexBatches=new List<Apex_Log__c>();
        initApexLogSetting();
    }

    //初始化
    private void initApexLogSetting(){
        OutputSystemDebugLogs=false;
        OutputDatabaseLogs=false;
        OutputOnlySpecifyClassLogs=false;
        UIShowException=false;
        UIDisplayDetailExceptions=false;
        UIDisplayFriendlyExceptions=false;
        SpecifyClasses='';
        List<Apex_Log_Setting__mdt> settings =getConfiguration();
        for (Apex_Log_Setting__mdt setting : settings) {
			switch on setting.DeveloperName {
				when 'Output_System_Debug_Logs' {
					OutputSystemDebugLogs = setting.Enabled__c;
                }
                when 'Output_Database_Logs' {
					OutputDatabaseLogs = setting.Enabled__c;
                }
                when 'Output_Only_Specify_Class_Logs' {
                    OutputOnlySpecifyClassLogs = setting.Enabled__c;
                    SpecifyClasses= setting.SpecifyClasses__c;
                }
                when 'UI_Show_Exception' {
					UIShowException = setting.Enabled__c;
                }
                when 'UI_Display_Detail_Exceptions' {
					UIDisplayDetailExceptions = setting.Enabled__c;
                }
                when 'UI_Display_Friendly_Exceptions' {
					UIDisplayFriendlyExceptions = setting.Enabled__c;
				}
			}
		}
    }

    //获取配置信息
    private List<Apex_Log_Setting__mdt> getConfiguration() {
		List<Apex_Log_Setting__mdt> settings = [SELECT DeveloperName, Enabled__c,SpecifyClasses__c FROM Apex_Log_Setting__mdt];
		return settings;
    }
    
    //保存Log
    public void Savelog(String severity, String className, String methodName, String message, Exception thrownException) {
        String exceptionMessage=buildExceptionMessage(thrownException);
		Apex_Log__c log = new Apex_Log__c(
			Severity__c = severity,
			Class__c = className,
			Method__c = methodName,
			Message__c = buildLogMessage(message, thrownException),
			Exception__c = exceptionMessage,
            WithException__c = (thrownException == BLANK_EXCEPTION) ? false : true,
            ExceptionType__c=thrownException.getTypeName()
        );
        systemDebug(message,exceptionMessage,log.Severity__c);
        saveToDatabase(log);
    }

    //通过System.debug输出
    private void systemDebug(String message,String exceptionMessage,String severity){
		if (this.OutputSystemDebugLogs) {
            System.debug(severityToLoggingLevel(severity), (String.isEmpty(message)?'':message+'\n')+exceptionMessage);
        }
    }
    //记录到Database
    private void saveToDatabase(Apex_Log__c log){
        //记录到Database
        if(this.OutputDatabaseLogs){
            //是否记录当前Class
            if(isRecordCurClass(log.Class__c)){
                //批次处理
                if(this.IsBatches){
                    this.ApexBatches.add(log);
                }
                else{
                    INSERT log;
                }
            }
        }
    }

    //是否记录当前Class
    private Boolean isRecordCurClass(String className){
        Boolean result=true;
        if(this.OutputOnlySpecifyClassLogs){
            result=false;
            if(String.isNotEmpty(this.SpecifyClasses)){
                List<String> parts =this.SpecifyClasses.split(',');
                if(parts.contains(className)){
                    result=true;
                }
            }
        }
        return result;
    }

    //批量保存并刷新
    public void flush() {
		if (!this.ApexBatches.isEmpty()) {
			insert this.ApexBatches;
			this.ApexBatches.clear();
		}
	}
    
    //构建错误消息
    private String buildLogMessage(String message, Exception thrownException) {
		if (String.isBlank(message)) {
			message = 'Exception thrown: ' + thrownException.getTypeName();
		}
		return message;
	}
    
    //获取LoggingLevel
    private LoggingLevel severityToLoggingLevel(String severity) {
		switch on severity {
			when 'DEBUG' { return LoggingLevel.DEBUG; }
			when 'INFO' { return LoggingLevel.INFO; }
			when 'WARN' { return LoggingLevel.WARN; }
			when 'ERROR' { return LoggingLevel.ERROR; }
			when else { return LoggingLevel.DEBUG; }
		}
    }
    
    //构建异常消息
	private String buildExceptionMessage(Exception thrownException) {
		String message = '';
		while (thrownException != BLANK_EXCEPTION && thrownException != null) {
			message += thrownException.getTypeName() + ': ' + thrownException.getMessage() + '\n';
			message += thrownException.getStackTraceString() + '\n\n';
			thrownException = thrownException.getCause();
		}
		return message;
    }
    
    //获取友好的异常
    public String getFriendlyExceptionMessage(String exceptionType){
        String message='';
        for(Schema.PicklistEntry pickItem: Apex_Log__c.ExceptionType__c.getDescribe().getPicklistValues()){
            if(exceptionType==pickItem.getValue()){
                message= pickItem.getLabel();
                break;
            }
        }
        return message;
    }
}